FROM python:3.11-slim
WORKDIR /ui
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY streamlit_app.py .
EXPOSE 8501
ENV STREAMLIT_SERVER_HEADLESS=true
CMD ["streamlit","run","streamlit_app.py","--server.port","8501","--server.address","0.0.0.0"]
