apiVersion: v1
kind: ConfigMap
metadata:
  name: palmer-config
  namespace: palmer
data:
  API_URL: "http://palmer-api.palmer.svc.cluster.local:8000"
  MODEL_PATH: "/app/storage/model.pkl"
  DB_HOST: "postgres"
  POSTGRES_DB: "palmerdb"
  POSTGRES_USER: "palmeruser"