apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: palmer-api-hpa
  namespace: palmer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: palmer-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
