apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: palmer
  namespace: palmer
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx        # <— add this line
  rules:
  - host: palmer.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: palmer-ui
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: palmer-api
            port:
              number: 8000
