apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palmer-model-pvc
  namespace: palmer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path

