apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx # In deployment, the labels/app:nginx must match
    spec:
      containers:
      - name: nginx
        image: nginx:1.16   # pinned version for stability
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort   # exposes nginx outside the cluster (handy in Minikube)
  selector:
    app: nginx # In service, the the selector/app:nginx must match the deployment labels/app:nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080   # fixed port for easy access via localhost:30080